# Generated by Django 6.0.6 on 2026-06-29 13:39

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0002_sport_remove_academy_sport_academy_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='academy',
            name='athlete_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Athlete Count'),
        ),
        migrations.AddField(
            model_name='academy',
            name='coach_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Coach Count'),
        ),
        migrations.AddField(
            model_name='academy',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='academy',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='GST Number'),
        ),
        migrations.AddField(
            model_name='academy',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Legal Name'),
        ),
        migrations.AddField(
            model_name='academy',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='academy',
            name='primary_contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Primary Contact Name'),
        ),
        migrations.AddField(
            model_name='academy',
            name='primary_contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Primary Contact Phone'),
        ),
        migrations.AddField(
            model_name='academy',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('proprietorship', 'Proprietorship'), ('partnership', 'Partnership'), ('private_limited', 'Private Limited'), ('trust', 'Trust'), ('society', 'Society'), ('other', 'Other')], max_length=32, verbose_name='Registration Type'),
        ),
        migrations.AddField(
            model_name='academy',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, verbose_name='Social Links'),
        ),
        migrations.AddField(
            model_name='academy',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
    ]
