# Generated by Django 6.0.6 on 2026-06-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0003_academy_address_academy_athlete_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('athlete', 'Athlete'), ('coach', 'Coach'), ('academy_admin', 'Academy Admin'), ('academy_head', 'Academy Head'), ('academy_staff', 'Academy Staff'), ('spectator', 'Spectator / Enthusiast'), ('parent_guardian', 'Parent / Guardian'), ('scout_recruiter', 'Scout / Recruiter')], max_length=16, verbose_name='Role'),
        ),
    ]
