"""Password reset token management backed by Django cache.

Provides :class:`PasswordResetHandler` — a singleton that generates,
stores, and validates single-use password reset tokens.  Tokens are
stored under the key ``pwd_reset:{token}`` with a configurable TTL
(default 15 minutes) and are consumed (deleted) on first use.

Token delivery is left to the caller; in development the
``ConsoleEmailService`` stub logs the token to stdout instead of sending
a real email.
"""

from __future__ import annotations

import secrets

from django.conf import settings
from django.core.cache import cache

_RESET_TOKEN_BYTES = 32  # 256-bit secure random token


class PasswordResetHandler:
    """Manages the full lifecycle of password reset tokens.

    Tokens are opaque hex strings generated by :mod:`secrets`.  They are
    stored in the Django cache (Redis in production) with a fixed TTL so
    they expire automatically even if never consumed.

    The cache key format is ``pwd_reset:{token}``; the stored value is the
    user's primary key (as a string).
    """

    KEY_PREFIX = "pwd_reset"
    DEFAULT_TTL = 15 * 60  # 15 minutes in seconds

    def _key(self, token: str) -> str:
        """Return the cache key for the given reset token."""
        return f"{self.KEY_PREFIX}:{token}"

    def generate_and_store(self, user_id: int | str) -> str:
        """Generate a secure reset token, persist it, and return it.

        Args:
            user_id: PK of the user requesting the password reset.

        Returns:
            A URL-safe hex string token valid for ``DEFAULT_TTL`` seconds.
        """
        token = secrets.token_hex(_RESET_TOKEN_BYTES)
        ttl = getattr(settings, "PASSWORD_RESET_TOKEN_TTL", self.DEFAULT_TTL)
        cache.set(self._key(token), str(user_id), timeout=ttl)
        return token

    def validate_and_consume(self, token: str) -> str | None:
        """Validate a reset token and delete it (single-use).

        Args:
            token: The hex token string submitted by the user.

        Returns:
            The user's PK string if the token is valid, ``None`` otherwise.
        """
        key = self._key(token)
        user_id = cache.get(key)
        if user_id:
            cache.delete(key)
        return user_id  # type: ignore[return-value]

    def ttl(self) -> int:
        """Return the configured token TTL in seconds."""
        return int(getattr(settings, "PASSWORD_RESET_TOKEN_TTL", self.DEFAULT_TTL))


password_reset_handler = PasswordResetHandler()
